---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: va-unraid-backup-rw
spec:
  capacity:
    storage: 100Ti
  accessModes:
    - ReadWriteMany
  storageClassName: "va-unraid-backup-rw"
  persistentVolumeReclaimPolicy: "Retain"
  mountOptions:
    - "vers=4.2,proto=tcp,port=2049"
  nfs:
    server: 10.0.20.180
    path: "/mnt/user/KubernetesBackup"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: va-unraid-backup-rw
  namespace: kasten
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: "va-unraid-backup-rw"
  resources:
    requests:
      storage: 100Ti
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    name: kasten
  name: kasten
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: k10
  namespace: kube-system
spec:
  repo: https://charts.kasten.io/
  chart: k10
  targetNamespace: kasten
  valuesContent: |-
    global:
      persistence:
        storageClass: mayastor-r1
