---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: va-unraid-backup-rw
spec:
  capacity:
    storage: 100Ti
  accessModes:
    - ReadWriteMany
  storageClassName: "va-unraid-backup-rw"
  persistentVolumeReclaimPolicy: "Retain"
  mountOptions:
    - "vers=4.2,proto=tcp,port=2049"
  nfs:
    server: 10.0.20.180
    path: "/mnt/user/KubernetesBackup"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: va-unraid-backup-rw
  namespace: kasten
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: "va-unraid-backup-rw"
  resources:
    requests:
      storage: 100Ti
---
apiVersion: v1
kind: Namespace
metadata:
  name: kasten
  labels:
    name: kasten
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: k10
  namespace: kube-system
spec:
  repo: https://charts.kasten.io/
  chart: k10
  targetNamespace: kasten
---
kind: Profile
apiVersion: config.kio.kasten.io/v1alpha1
metadata:
  name: k10-backup-profile
  namespace: kasten
spec:
  locationSpec:
    type: FileStore
    fileStore:
      claimName: va-unraid-backup-rw
    credential:
      secretType: ""
      secret:
        apiVersion: ""
        kind: ""
        name: ""
        namespace: ""
  type: Location
---
apiVersion: config.kio.kasten.io/v1alpha1
kind: TransformSet
metadata:
  name: storage-class-rename
  namespace: kasten
spec:
  comment: Renames cstor-r1 to truenas-iscsi
  transforms:
    - json:
        - op: replace
          path: /spec/storageClassName
          value: truenas-iscsi
      name: StorageClassRename
      subject:
        name: ""
        resource: persistentvolumeclaims
