---
# Namespace
apiVersion: v1
kind: Namespace
metadata:
  labels:
    name: longhorn
  name: longhorn

---
# HelpChart
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: longhorn
  namespace: kube-system
spec:
  repo: https://charts.longhorn.io
  chart: longhorn
  targetNamespace: longhorn
  valuesContent: |-
    persistence:
      defaultClass: true
      defaultClassReplicaCount: 3
      reclaimPolicy: Delete

    defaultSettings:
      defaultDataPath: /storage/longhorn
      defaultReplicaCount: 3
      nodeDownPodDeletionPolicy: delete-both-statefulset-and-deployment-pod
      guaranteedEngineManagerCPU: 0.25
      guaranteedReplicaManagerCPU: 0.25

    longhornManager:
      tolerations:
      - key: "node-role.kubernetes.io/control-plane"
        operator: "Exists"
        effect: "NoSchedule"
---
# StorageClass
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: longhorn-block-triple
provisioner: driver.longhorn.io
allowVolumeExpansion: true
parameters:
  numberOfReplicas: "3"
  staleReplicaTimeout: "2880"
  fsType: "ext4"
